screwdriver-cd/scm-bitbucket

README.md, index.js, package.json, screwdriver.yaml, test/data/pr.closed.json, test/data/pr.opened.json, test/data/repo.push.json, test/index.test.js
This is blocked by https://github.com/screwdriver-cd/scm-base/pull/11
Relates to https://github.com/screwdriver-cd/screwdriver/issues/255
=> parse webhook payload

index.js, test/index.test.js
=> Add json:true option for request

index.js, test/index.test.js
`access_key` should have been `access_token`. 
- I changed it to be inside `options` since that makes the code look better. 
- JSON.stringify the body for error message.
=> Fix bug: wrong url param

README.md, index.js, package.json, test/index.test.js
Get bell configuration for bitbucket
=> Add bell configuration

index.js, test/index.test.js
Because of this https://github.com/screwdriver-cd/data-schema/pull/81
=> Add hookId

index.js, package.json, test/index.test.js
- Switch to promise for _parseHook
=> Use promise for _parseHook

index.js, test/index.test.js
Better error message
Relates to https://github.com/screwdriver-cd/screwdriver/issues/297
=> Better error message when repo does not exist

CHANGELOG.md, index.js, package.json, test/data/commands.json, test/data/prCommands.json, test/index.test.js
- Generate checkout code in bitbucket plugin
Related to https://github.com/screwdriver-cd/screwdriver/issues/312
=> Generate checkout code in bitbucket plugin

package.json, screwdriver.yaml
Use semantic-release to publish
=> feat: Use semantic-release to publish

package.json
=> fix: Update joi to version 10.0.5

index.js, test/index.test.js
Add getOpenedPRs
Related: https://github.com/screwdriver-cd/screwdriver/issues/417
=> feat: Add _getOpenedPRs for BitBucket

index.js, test/index.test.js
Fixes to addWebhook, createWebhook, findWebhook, getOpenedPRs for making requests using proper inputs.
Also fixed small issue with changing array to object
=> fix: Fixed input format for requests

index.js, test/index.test.js
feat: add _getPrInfo function
Blocked by https://github.com/screwdriver-cd/scm-base/pull/39
Related to https://github.com/screwdriver-cd/screwdriver/issues/244
=> feat: add _getPrInfo function

index.js, package.json, test/index.test.js
Related: https://github.com/screwdriver-cd/screwdriver/issues/471
=> fix: includes pipelineId in description

index.js, package.json, test/index.test.js
add url to pull request info gathered
related: https://github.com/screwdriver-cd/screwdriver/issues/822
=> fix: add url to getprinfo

index.js, test/index.test.js
To get pipelines, we need a function which get list of branch.
Implement getBranchList function.
[bitbucket api](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/refs/branches)
Blocked by 
- https://github.com/screwdriver-cd/data-schema/pull/240
- https://github.com/screwdriver-cd/scm-base/pull/57
Related to screwdriver-cd/screwdriver#1082
=> feat(1082): [4] implement getBranchList function

CONTRIBUTING.md, package.json, test/index.test.js
=> fix: Update dependencies for security

index.js, package.json, test/data/access.token.json, test/index.test.js
This PR will merge in the fix for 1713, which will allow the Bitbucket SCM to use an access token that is renew after the given expiration interval.  Bitbucket has a 2 hour expiration for each access token it generates.
This PR will fix the access token expiration by knowing when to refresh the access token.  This PR also updates any methods that are previously not async, into async method to properly support grabbing/refreshing the token.
This PR is to fix https://github.com/screwdriver-cd/screwdriver/issues/1713.
=> Merging fix for issue 1713

index.js, test/index.test.js
Fixes screwdriver-cd/screwdriver#1415
Add custom actions to addWebhook
screwdriver-cd/screwdriver#1415
=> feat(1415): Add custom actions to addWebhook

index.js
Fixes screwdriver-cd/screwdriver#1415
=> fix(1415): Fix function definition and event map object

.gitignore, index.js, package.json, test/index.test.js
This PR updates eslint-config-screwdriver package to v5.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2492
=> feat(2492): Update to eslint-config-screwdriver v5

index.js
Porting https://github.com/screwdriver-cd/scm-github/pull/203 for gitlab
=> fix(2427): The source directory function works even when the target directory is created by PR.

index.js, test/index.test.js
Same as https://github.com/screwdriver-cd/scm-gitlab/pull/52
=> fix: throws statusCode on parseUrl
