README.md, index.js, package.json, test/index.test.js
- Takes care of https and ssh url
- We need to pass these fields to make calls to Bitbucket API:
```
login_type: 'oauth2',
oauth_access_token: config.token
```
Relates to https://github.com/screwdriver-cd/screwdriver/issues/255
=> Add parseUrl function for Bitbucket

README.md, index.js, package.json, test/index.test.js
Add decorated functions:
- `_decorateUrl`
- `_decorateAuthor`
- `_decorateCommit`
Also remove breaker mock and mock request directly instead
Relates to https://github.com/screwdriver-cd/screwdriver/issues/255
=> Add decorated functions

README.md, index.js, test/index.test.js
Because some endpoints are not available in V2 yet, we need to use V1 for some of the functions. 
Also, there is no way to check permission of an authenticated user against a repo like in Github. The `privileges` endpoint requires access token of the repo owner. A workaround is just making calls to repositories/:owner?role=admin (or contributor) and check if the repo name is in the list.
~~I'll make another PR for `updateCommitStatus`. For a POST, I passed it in like this: `auth: { bearer: token }` but it keeps saying token expired. So I'll try to figure that out next.~~
Added `updateCommitStatus`. _Reason was the token is encoded, so I have to decode it first_ 
Resource: https://answers.atlassian.com/questions/31673283/what-is-the-best-way-to-check-a-permission-granted-to-the-currently-au …
=> Add getCommitSha, getFile, getPermissions, updateCommitStatus

index.js, test/index.test.js
Fix a couple bugs:
- Oauth is inside `this.config`
- parseHook for PR branch should return the destination instead of source branch
- parseUrl: uuid is inside `repository`
- prRef is just going to be the source branch since bitbucket.org does not have prRef.
=> [3] Pass in oauth object correctly

index.js, test/index.test.js
- Bitbucket returns 201 for POST
- Fix bug to check against 201
- Via Bitbucket UI, you can decline a PR which is the same as close a PR
=> Fix bug: POST returns 201 and set decline PR as closed

index.js, test/index.test.js
- Bitbucket API returns 201 for updating commit status if it is the first update for the sha
- It returns 200 for updating commit status if it is not the first update for the same sha
=> Accept 200 as success for updating commit status

index.js, test/data/pr.closed.json, test/data/pr.opened.json, test/data/repo.push.json, test/index.test.js
- Since creating Events will require a `creator`, fixing bug in parseHook method to return creator instead of author for pull_request event
- Updated mock data to make sure new changes are working
- Also caught a bug where `checkoutUrl` should have the repo owner, not author username
Will need this information for creating Events in webhooks in Screwdriver API
=> Return creator, not author, for pull request event

index.js, test/data/pr.sync.json, test/index.test.js
Bitbucket will send a `pullrequest:updated` when amending commits to an opened PR. This is equivalent to `synchronized` in Github.
=> Handle PR sync

index.js, package.json, test/data/commands.json, test/data/prCommands.json
Adding `sd-` as a prefix for the command name to avoid stepping on user configs
Blocked by https://github.com/screwdriver-cd/scm-base/pull/29
=> [4] Checkout command name should be sd-checkout-command

index.js, test/data/commands.json, test/data/prCommands.json
- Switching to using an absolute path when running `git clone` so the src dir will be consistent in the launcher
- SD_SOURCE_DIR is an environment variable set in the launcher
https://github.com/screwdriver-cd/launcher/blob/master/launch.go#L236
Related to https://github.com/screwdriver-cd/screwdriver/issues/312
=> Git clone to $SD_SOURCE_DIR

index.js, test/data/commands.json, test/data/prCommands.json, test/index.test.js
A mirror of screwdriver-cd/scm-github#45. This PR implements a non-public(ish) method that adds a webhook to a Bitbucket.org repository. If the repo already has a Screwdriver webhook, it will also update the webhook to ensure that it has all the correct information(e.g., permission scope).
Contributes to screwdriver-cd/screwdriver#379
EDIT: Link to the correct issue
=> feat(379): addWebhook to attach a webhook URL to a repo

CHANGELOG.md, package.json, test/.eslintrc.yaml, test/index.test.js
This should not affect affect the SCM module as it doesn't depend on any of the id => hash specific changes.
Blocked on: https://github.com/screwdriver-cd/scm-base/pull/35
Epic: https://github.com/screwdriver-cd/screwdriver/issues/399
=> fix(399): Catching up to new version of `data-schema`

README.md, index.js, test/data/customPrCommands.json, test/index.test.js
I want to use own username and email for checkout from Bitbucket.
like this: https://github.com/screwdriver-cd/scm-github/pull/52
=> fix: can settings username and email for bitbucket checkout

index.js, test/index.test.js
When testing locally I kept on getting an error "Can't read uuid of undefined" so I looked into the response object from bitbucket
I saw in practice that it's returned in `response.body.target.respository` instead of just `response.body.respository`
I went looking through the [documentation](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/refs/branches/%7Bname%7D) which states that the default response is an error object..
And I couldn't find any swagger object definitions that document this return type. This fixed it for me, but I'm not sure what the right thing to do is..
=> fix: Bitbucket api returns repository information under the target object

index.js, test/index.test.js
I'd like to implement the skipping builds feature (screwdriver-cd/screwdriver#587)
I've already changed `scm-github` module to do it (screwdriver-cd/scm-github#64)
This PR adds lastCommitMessage to the result of `parseHook`.
- issue: screwdriver-cd/screwdriver#587
- webhook spec: https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-Push
=> feat(587): Add lastCommitMessage to parsed hook

screwdriver.yaml
Pulling in new workflow and getting rid of duplicate semantic release steps
=> fix: Use new workflow and template

index.js, package.json, test/index.test.js
Adding the getChangedFiles method to bitbucket but they don't have any ways to actually get the changed files.
This PR implements `getChangedFiles` to just resolve null.
Original issue: https://github.com/screwdriver-cd/screwdriver/issues/911
Blocked by: https://github.com/screwdriver-cd/data-schema/pull/219
=> feat(911): Add getChangedFiles method

index.js, screwdriver.yaml, test/index.test.js
Node.js 6 is slowly becoming deprecated, with popular packages such as `semantic-release` no longer supporting it.
* Change image in `screwdriver.yaml` to `node:8`
* Bump up coverage to 100%
* Minor whitespacing and JSDoc changes, for consistency
=> refactor(hip): Upgrade to node:8

index.js, test/index.test.js
In order to remove pipelines for repositories that do not exist, the `getPermissions` interface needs to first uniformly check if a repository exists, and if not, throw an error with `code: 404`. 
In the case of `scm-bitbucket`, the implementation of this method does not throw a 404 for a missing repository. Instead it checks this [endpoint](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D) for permissions on all repositories.
Additionally changing `url` to `webhookUrl` in `_addWebhook` to be in accordance with the [interface](https://github.com/screwdriver-cd/scm-base#addwebhook).
In `getPermissions`, first check that the repository exists. If not, throw a 404.
https://github.com/screwdriver-cd/screwdriver/issues/450
=> fix(450): Check if repo exists before getting permissions

index.js, test/index.test.js
**Issue #, if available:** https://github.com/screwdriver-cd/screwdriver/issues/1646
When `pipeline.prSync` is called, it needs base branch info for the PR to get next job for `~pr:<branchName>`.
**Description of changes:**
This PR allow `getPrInfo` to return `baseBranch` value which contains the base branch name of a PR.
This PR is requires below changes before merge.
https://github.com/screwdriver-cd/scm-base/pull/70
https://github.com/screwdriver-cd/data-schema/pull/339
I confirm that this contribution is made under the terms of your choice and that I have the authority necessary to make this contribution on behalf of its copyright owner.
=> fix(1646): [4] add baseBranch to return value in getPrInfo

index.js, test/index.test.js
We need to update the getFile request to use the Bitbucket API 2.0 since API 1.0 is deprecated and no longer works.
This PR will fix bug request #1689.
References bug request #1689
=> Bitbucket API 2.0 Update for #1689

index.js, test/index.test.js
With the update of the getFile to use the Bitbucket API 2.0, the response no longer is a JSON object, it is naw the raw file.  In order to support this, we need to return response.body instead of response.body.data.
This PR fixes the Bitbucket file download.
The bug report for this is #1689.
=> Fix getFile value to response.body

index.js, package.json, test/index.test.js
Since we are removing setting default branch in API/UI, we will need to set it in the plugin.
This PR sets the default branch to `master` while we wait for bitbucket add a default branch field.
Bitbucket issue: https://jira.atlassian.com/browse/BCLOUD-20212
Related to https://github.com/screwdriver-cd/screwdriver/issues/2185
=> fix(2185): Add default branch (hardcode for now) [1.5]

index.js, package.json, screwdriver.yaml
Screwdriver hapi.js dependencies are outdated and not supported anymore.
This PR majorly upgrades @hapi/joi version and fixes all schema related changes to be compatible with latest @hapi js dependencies.
https://github.com/screwdriver-cd/screwdriver/issues/1958
=> feat: upgrade hapiv19 dependencies. BREAKING CHANGE: scm-base version

index.js, package.json, test/index.test.js
Scms are using different error objects and API does not handle GitLab error objects.
e.g. https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/webhooks/index.js#L405
These errors should be handled by API.
- Error object has status property instead of code property.
- Error message use body.error.detail instead of body.error.detail.required
- https://github.com/screwdriver-cd/screwdriver/issues/2367
- https://github.com/screwdriver-cd/scm-gitlab/pull/36/
- [Bitbucket error response example](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/hooks)
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary …
=> fix:[2] Unify error objects with GitHub errors.

index.js, test/index.test.js
Getting error with `_refreshToken()`:
```
api_1    | 210906/113528.737, (1630928128201:e464b22cc7bb:20:kt8k149p:10045) [request,server,error] data: SyntaxError: Unexpected token o in JSON at position 1
api_1    |     at JSON.parse (<anonymous>)
api_1    |     at BitbucketScm._refreshToken (/usr/src/app/node_modules/screwdriver-scm-bitbucket/index.js:1042:27)
api_1    |     at runMicrotasks (<anonymous>)
api_1    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
api_1    |     at async BitbucketScm._getToken (/usr/src/app/node_modules/screwdriver-scm-bitbucket/index.js:1006:13)
api_1    |     at async BitbucketScm._parseUrl (/usr/src/app/node_modules/screwdriver-scm-bitbucket/index.js:322:23)
api_1    |     at async handler …
```
=> fix(1961): Response does not need to be JSON parsed

index.js, package.json, test/index.test.js
In order to support getting provider config dynamically in screwdriver.yaml, we need to be able to pass in the full path to getFile instead of the scmUri, etc.
This PR changes getFile method to allow using full path to get repo owner, name, branch, etc info.
https://github.com/screwdriver-cd/screwdriver/issues/2676
Related to https://github.com/screwdriver-cd/scm-github/pull/204
=> feat(2676): Support passing in full path for getFile

index.js, package.json, test/index.test.js
Bitbucket SCM is unable to fetch `screwdriver.yaml` after version >=4.5.0. This is likely related to the change to using screwdriver-request package.
This PR switches to taking in file as buffer to avoid screwdriver-request package [throwing error on 200](https://github.com/sindresorhus/got/blob/0703318d3bb6cc1340614612d2ae14b23f651242/source/core/response.ts#L141). Also adds try/catch around decorateAuthor and getFile.
Also adds try/catch to request calls.
_Note: decorateAuthor will return empty for now because of bitbucket's switch from username -> UUID._
Announcement: https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/
Related issues: https://stackoverflow.com/questions/53983942/how-to-find-bitbucket-account-uuid, …
=> fix(2690): Get file as buffer

index.js, test/index.test.js
Users in Bitbucket can perform below restricted operations on a pipeline associated with repository for which they do not have access (admin/write)
Add/Update secrets
Add/Update tokens
Start build
Sync Pipeline/PRs
.... and more
Use token associated with the logged in user to fetch the permissions from SCM for the pipeline repository.
This would forbidden above mentioned operations in the Screwdriver to the user without write/admin access the the pipeline SCM repository.
https://github.com/screwdriver-cd/screwdriver/issues/2858
=> fix(2858): Bitbucket - Users without access to a SCM repo can manage the associated pipeline in Screwdriver

index.js, test/index.test.js
The following PR needs to get a SCM user id.
https://github.com/screwdriver-cd/screwdriver/pull/2890
This PR will include a BitBucket id in the return value of `decorateAuthor`.
This PR will add a BitBucket id in the return value of `decorateAuthor`.
I cannot actually test this by BitBucket API, so try this please.
Issue
- https://github.com/screwdriver-cd/screwdriver/issues/2892
=> feat(2892): get BitBucket user ID

index.js, test/data/issue.create.json, test/data/pr.commentCreate.json, test/data/repo.fork.json, test/index.test.js
Currently, the `_parseHook` method  returns Object or null or throw Error.
However, their return values are not properly conditioned.
Organize the return values by the following:
- return Object (parsed result): the `scm` is correct and Screwdriver do actions with the webhook (e.g. `push` event)
- return null: the `scm` is correct and Screwdriver do nothing (e.g. `delete` event)
- throw Error: the `scm` is not correct
Then we can handle whether the webhook is correct or not at [here](https://github.com/screwdriver-cd/screwdriver/blob/ef31fca55eaff2548f7486795de41e84f87a675d/plugins/webhooks/index.js#L68-L73).
Issue
- https://github.com/screwdriver-cd/screwdriver/issues/3225
PR
- https://github.com/screwdriver-cd/scm-router/pull/37
I confirm that this contribution is made under the terms …
=> fix(3225): organize the return values of _parseHook [3]

index.js, test/index.test.js
SD configuration currently does not support pull_request closed trigger, to enable this feature we need to additional parsed information from webhook
This PR adds `prMerged` flag to parsed webhook response
https://github.com/screwdriver-cd/data-schema/pull/597
=> feat: add prMerged flag to webhook result 

package.json, test/index.test.js
Changes made in the https://github.com/screwdriver-cd/scm-base/pull/101 has resulted in few test failures
Adapt the tests to align with the latest changes
https://github.com/screwdriver-cd/screwdriver/issues/3384
=> fix(3384): Failure to get user info from scm should not throw error
